### ISSUE TITLE
USER STORY: Location

### ISSUE THREAD

**Issue by 0DylanMcMahon** [0NETRUNNER/InkedClippers#11]
# Epic: Landing page 

As a **customer**, I want to **easily find the location or address of the barbershop or tattoo studio**, so that **I can plan my visit or contact them if needed**.

## Tasks: - [ ]

- [x] Task 1: Include a section on the landing page that displays the location or address of the business.

- [x] Task 2: Add a map or directions to make it easy for visitors to find the location.

- [x] Task  3: Ensure the location section is prominently placed and provides clear information.
