### ISSUE TITLE
USER STORY: First deployment

### ISSUE THREAD

**Issue by 0DylanMcMahon** [0NETRUNNER/InkedClippers#13]
# EPIC: First Deployment

As a **developer** I want to **perform an initial deployment of my Django project to Heroku** so that I can **quickly test and verify its functionality in a live environment**.

## Tasks:

- [x] Task 1. Make a new app in Heroku

- [x] Task 2.  Create a Database on ElephantSQL

- [x] Task 3. Hide convig vars
