### ISSUE TITLE
USER STORY: User Registration

### ISSUE THREAD

**Issue by 0DylanMcMahon** [0NETRUNNER/InkedClippers#14]
# Epic: Sign up

As a **customer**, I want to **register for the website**  so that I can **access the features and functionalities**.

## Tasks: - [ ]

- [x] Task 1. Design and implement a registration page with the required fields.

- [x] Task 2. Display appropriate success or error messages based on the registration outcome.

- [x] Task 3. Create a login option or link for users who already have an account.
