### ISSUE TITLE
USER STORY: Login/Logout

### ISSUE THREAD

**Issue by 0DylanMcMahon** [0NETRUNNER/InkedClippers#15]
# Epic: LogIn/Logout

As a **customer** I want to be able to **log in and log out** of the website so that I can **have an account to save my information so I dont have to enter it every time**.

## Tasks: - [ ]

- [x] Task 1. Develop the backend logic to validate user login credentials.

- [x] Task 2. Display appropriate error messages for invalid login attempts.

- [x] Task 3. Create Login/Logout pages
